export default {
  // Include any build-time environment variables
  build: {
    env: {
      REACT_APP_FIREBASE_API_KEY: import.meta.env.VITE__FIREBASE_API_KEY,
      REACT_APP_FIREBASE_AUTH_DOMAIN: import.meta.env.VITE__FIREBASE_AUTH_DOMAIN,
      REACT_APP_FIREBASE_PROJECT_ID: import.meta.env.VITE__FIREBASE_PROJECT_ID,
      REACT_APP_FIREBASE_STORAGE_BUCKET: import.meta.env.VITE__FIREBASE_STORAGE_BUCKET,
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE__FIREBASE_MESSAGING_SENDER_ID,
      REACT_APP_FIREBASE_APP_ID: import.meta.env.VITE__FIREBASE_APP_ID,
      REACT_APP_FIREBASE_MEASUREMENT_ID: import.meta.env.VITE__FIREBASE_MEASUREMENT_ID
    }
  }
} 