services:
  - type: web
    name: borough
    env: node
    buildCommand: cd ui && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: POSTGRES_USER
        fromDatabase:
          name: borough-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: borough-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: borough-postgres
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: borough-postgres
          property: database

databases:
  - name: borough-postgres
    databaseName: borough-postgres
    user: borough-postgres
    plan: free